### ISSUE TITLE
add ROS gencpp and genmsg

### ISSUE THREAD

**Issue by dagar** [PX4/homebrew-px4#19]
This are available as mainline Ubuntu packages (without ROS), so if added here we can easily drop them as Firmware submodules. https://github.com/PX4/Firmware/blob/master/.gitmodules#L8-L13

gencpp
 - http://wiki.ros.org/gencpp
 - https://github.com/ros/gencpp

genmsg
 - http://wiki.ros.org/genmsg
 - https://github.com/ros/genmsg

**Comment by LorenzMeier** [comment]
Closing as we seem to be doing fine right now.
