### ISSUE TITLE
Error: Cannot tap px4/px4: invalid syntax in tap!

### ISSUE THREAD

**Issue by BrandonOsas** [PX4/homebrew-px4#20]
> ==> Tapping px4/px4
Cloning into '/usr/local/Homebrew/Library/Taps/px4/homebrew-px4'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 5), reused 5 (delta 2), pack-reused 0
Unpacking objects: 100% (17/17), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/px4/homebrew-px4/qt54.rb
Calling BottleSpecification.revision is disabled!
Use BottleSpecification.rebuild instead.
/usr/local/Homebrew/Library/Taps/px4/homebrew-px4/qt54.rb:21:in `block in <class:Qt54>'
Please report this to the px4/px4 tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap px4/px4: invalid syntax in tap!

**Comment by LorenzMeier** [comment]
Fixed! https://github.com/PX4/homebrew-px4/commit/89ea200051be4679ceaa4c8f7ad9dcd0b478df26
