### ISSUE TITLE
Error: Cannot tap ardupilot/px4: invalid syntax in tap!

### ISSUE THREAD

**Issue by CALICAWESOME** [PX4/homebrew-px4#63]
> ==> Tapping ardupilot/px4
> Cloning into '/usr/local/Homebrew/Library/Taps/ardupilot/homebrew-px4'...
> remote: Enumerating objects: 242, done.
> remote: Total 242 (delta 0), reused 0 (delta 0), pack-reused 242
> Receiving objects: 100% (242/242), 305.35 KiB | 4.85 MiB/s, done.
> Resolving deltas: 100% (137/137), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ardupilot/homebrew-px4/kconfig-frontends.rb
> kconfig-frontends: Calling a Formula#patches definition is disabled! Use 'patch do' block calls instead.
> Please report this issue to the ardupilot/px4 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/ardupilot/homebrew-px4/kconfig-frontends.rb:23
> 
> Error: Cannot tap ardupilot/px4: invalid syntax in tap!

**Comment by LorenzMeier** [comment]
This is for PX4, not APM, so please report in the correct issue tracker.
