### ISSUE TITLE
homebrew deprecated the java formula

### ISSUE THREAD

**Issue by mrpollo** [PX4/homebrew-px4#64]
The formula is giving / warnings due to the java dependency, it's now deprecated in favor of openjdk

```
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the px4/px4 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
```

We need to update our formulas to target `openjdk`, according to the `jMAVSim` repo we need Java 8 or greater 

https://github.com/PX4/jMAVSim

**Comment by mrpollo** [comment]
**NOTE**: this seems to be affecting versions of homebrew above 2.6.0

**Comment by LorenzMeier** [comment]
Thanks for reporting! This is fixed.
